FROM golang:1.21.5-alpine as builder
WORKDIR /build
COPY go.mod . 
RUN go mod download
COPY . .
RUN go build -o client ./cmd/client/main.go

FROM docker:24.0.5
COPY --from=builder /build/client /bin/oeda
RUN chmod +x /bin/oeda
