services:
  client:
    build: 
      context: .
      args:
        - service=agent
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SERVER_IP=10.10.124.53
